<%--*******************************
    * Name: Eduardo Go Matsushita *
    * Student Id: 300904663       *
    *******************************--%>

<%@ Page Title="Book Details" Language="C#" MasterPageFile="~/LibraryCollection.master" AutoEventWireup="true" CodeFile="BookDetails.aspx.cs" Inherits="BookDetails" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolderContent" Runat="Server">   
    <div class="col-sm-offset-2 col-sm-8">
        <asp:literal ID="list" runat="server"></asp:literal>
    </div>
    <div class="col-sm-offset-2 col-sm-8">
        <asp:DetailsView ID="bookDetails" runat="server" AutoGenerateRows="False" DataKeyNames="idLibCol" DataSourceID="bookDataSource" AutoGenerateDeleteButton="True" FieldHeaderStyle-CssClass="col-sm-3 header-field">
            <Fields>
                <asp:BoundField DataField="idLibCol" HeaderText="ID" ReadOnly="True" SortExpression="idLibCol" InsertVisible="False" />
                <asp:BoundField DataField="title" HeaderText="Title" SortExpression="title" />
                <asp:BoundField DataField="author" HeaderText="Author" SortExpression="author" />
                <asp:BoundField DataField="isbn" HeaderText="ISBN" SortExpression="isbn" />
                <asp:BoundField DataField="genre" HeaderText="Genre" SortExpression="genre" />
                <asp:BoundField DataField="pages" HeaderText="Pages" SortExpression="pages" />
                <asp:BoundField DataField="landedFriend" HeaderText="Landed to a Friend" SortExpression="landedFriend" />
                <asp:BoundField DataField="nameFriend" HeaderText="Name of a Friend" SortExpression="nameFriend" />
                <asp:BoundField DataField="comments" HeaderText="Comments" SortExpression="comments" />
            </Fields>
        </asp:DetailsView>
        <asp:SqlDataSource ID="bookDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:LibraryCollection %>" 
                           SelectCommand="SELECT * FROM [booksCol] WHERE ([title] = @title)"
        >
            <SelectParameters>
                <asp:QueryStringParameter QueryStringField="det" Name="title" Type="String"></asp:QueryStringParameter>
            </SelectParameters>
            <SelectParameters>
            </SelectParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>

<%--*******************************
    * Name: Eduardo Go Matsushita *
    * Student Id: 300904663       *
    *******************************--%>