<%--*******************************
    * Name: Eduardo Go Matsushita *
    * Student Id: 300904663       *
    *******************************--%>

<%@ Page Title="Book Details" Language="C#" MasterPageFile="~/LibraryCollection.master" AutoEventWireup="true" CodeFile="BookDetails.aspx.cs" Inherits="BookDetails" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolderContent" Runat="Server">   
    <div class="col-sm-offset-2 col-sm-8">
        <asp:literal ID="lit" runat="server"></asp:literal>
        <asp:detailsview id="bookDetails" runat="server" autogeneraterows="False" 
                         datakeynames="idLibCol" datasourceid="bookDataSource" autogeneratedeletebutton="True" 
                         OnItemDeleted="bookDetails_ItemDeleted" 
        >            
            <Fields>
                <asp:BoundField DataField="idLibCol" HeaderText="idLibCol" SortExpression="idLibCol" ReadOnly="True" />
                <asp:BoundField DataField="title" HeaderText="title" SortExpression="title" />
                <asp:BoundField DataField="author" HeaderText="author" SortExpression="author" />
                <asp:BoundField DataField="isbn" HeaderText="isbn" SortExpression="isbn" />
                <asp:BoundField DataField="genre" HeaderText="genre" SortExpression="genre" />
                <asp:BoundField DataField="pages" HeaderText="pages" SortExpression="pages" />
                <asp:BoundField DataField="landedFriend" HeaderText="landedFriend" SortExpression="landedFriend" />
                <asp:BoundField DataField="nameFriend" HeaderText="nameFriend" SortExpression="nameFriend" />
                <asp:BoundField DataField="comments" HeaderText="comments" SortExpression="comments" />
            </Fields>
        </asp:detailsview>
        <asp:linkbutton runat="server" CssClass="btn-back" postbackurl="~/Books.aspx">Back</asp:linkbutton>

<%--*******************************
    * Name: Eduardo Go Matsushita *
    * Student Id: 300904663       *
    *******************************--%>

        <asp:sqldatasource id="bookDataSource" runat="server" connectionstring="<%$ ConnectionStrings:LibraryCollection %>"
                           selectcommand="SELECT * FROM [booksCol] WHERE ([idLibCol] = @idLibCol)">
            <SelectParameters>
                <asp:SessionParameter Name="idLibCol" SessionField="idLibCol" Type="Int32" />
            </SelectParameters>
        </asp:sqldatasource>
    </div>
</asp:Content>

<%--*******************************
    * Name: Eduardo Go Matsushita *
    * Student Id: 300904663       *
    *******************************--%>